In [8]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25

pandas-dataframe

In [9]:
import pandas as pd

## series - similar to 1D array
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
## Create a Series from dictionary
data = {'a':1 ,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [11]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [12]:
## Dataframe
## create a Dataframe from a dictionary oof list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

In [10]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [11]:
import numpy as np
np.array(df)

array([['Krish', 32, 'Bangalore'],
       ['John', 34, 'Bangalore'],
       ['Bappy', 32, 'Bangalore'],
       ['JAck', 32, 'Bangalore']], dtype=object)

In [12]:
import pandas as pd
df = pd.read_csv(r'C:\Users\ROHIT HALDER\test_ML_LEARN_PRACTICE_DAILY\dataSet\sales_data.csv')
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [13]:
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [14]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [15]:
#access data from data frame
data

[{'Name': 'Krish', 'Age': 32, 'City': 'Bangalore'},
 {'Name': 'John', 'Age': 34, 'City': 'Bangalore'},
 {'Name': 'Bappy', 'Age': 32, 'City': 'Bangalore'},
 {'Name': 'JAck', 'Age': 32, 'City': 'Bangalore'}]

In [16]:
df['Product Category']

0          Electronics
1      Home Appliances
2             Clothing
3                Books
4      Beauty Products
            ...
235    Home Appliances
236           Clothing
237              Books
238    Beauty Products
239             Sports
Name: Product Category, Length: 240, dtype: object

.loc → “Look by name”
.iloc → “Look by number”

In [18]:
## df.loc[x] is used in pandas to access rows (and optionally columns) by label (index name)
df.loc[[0,1,2]]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [22]:
##iloc in pandas is used for position-based indexing (i.e., using row/column numbers, not labels).
df.iloc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [27]:
df.at[2 , 'Product Name']

"Levi's 501 Jeans"

In [28]:
df.iat[2,3]

"Levi's 501 Jeans"

In [35]:
df.drop('Product Name', axis=1, inplace=True)
df

,Transaction ID,Date,Product Category,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,29.99,59.98,Asia,Credit Card

In [36]:
df.describe()

       Transaction ID   Unit Price  Total Revenue
count       240.00000   240.000000     240.000000
mean      10120.50000   236.395583     335.699375
std          69.42622   429.446695     485.804469
min       10001.00000     6.500000       6.500000
25%       10060.75000    29.500000      62.965000
50%       10120.50000    89.990000     179.970000
75%       10180.25000   249.990000     399.225000
max       10240.00000  3899.990000    3899.990000

In [46]:
df_Data = pd.read_csv(r'C:\Users\ROHIT HALDER\test_ML_LEARN_PRACTICE_DAILY\dataSet\sales1_data.csv')
df_Data.head()
## Handling Missing Values
#df_Data.isnull().any()

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East

In [47]:
df_Data.describe()

            Sales
count   19.000000
mean   554.000000
std    231.543372
min    124.000000
25%    381.500000
50%    554.000000
75%    737.500000
max    868.000000

In [48]:
df_Data.isnull()

     Date  Product  Sales  Region
0   False    False  False   False
1   False    False  False   False
2   False    False  False   False
3   False    False  False   False
4   False    False  False   False
5   False    False   True   False
6   False    False  False   False
7   False    False  False   False
8   False    False  False   False
9   False    False  False   False
10  False    False  False   False
11  False    False   True   False
12  False    False   True   False
13  False    False  False   False
14  False    False  False   False
15  False    False  False   False
16  False    False   True   False
17  False    False   True   False
18  False    False  False   False
19  False    False  False   False
20  False    False   True   False
21  False    False  False   False
22  False    False  False   False
23  False    False  False   False
24  False    False  False   False

In [50]:
df_Data.isnull().any()

Date       False
Product    False
Sales       True
Region     False
dtype: bool

In [51]:
### filling missing values with the mean of the column
df_Data['Sales_fillNA']=df_Data['Sales'].fillna(df_Data['Sales'].mean())
df_Data

          Date   Product  Sales Region  Sales_fillNA
0   2023-01-01  Product3  738.0   West         738.0
1   2023-01-02  Product2  868.0  North         868.0
2   2023-01-03  Product2  554.0   West         554.0
3   2023-01-04  Product1  618.0  South         618.0
4   2023-01-05  Product3  501.0   East         501.0
5   2023-01-06  Product1    NaN   West         554.0
6   2023-01-07  Product3  339.0  South         339.0
7   2023-01-08  Product3  280.0  South         280.0
8   2023-01-09  Product2  806.0  North         806.0
9   2023-01-10  Product2  816.0  South         816.0
10  2023-01-11  Product3  469.0   West         469.0
11  2023-01-12  Product3    NaN   East         554.0
12  2023-01-13  Product3    NaN   East         554.0
13  2023-01-14  Product3  676.0   East         676.0
14  2023-01-15  Product1  183.0  South         183.0
15  2023-01-16  Product1  424.0  South         424.0
16  2023-01-17  Product1    NaN  South         554.0
17  2023-01-18  Product1    NaN  South         554.0
18  2023-01-19  Product2  124.0  North         124.0
19  2023-01-20  Product3  732.0   West         732.0
20  2023-01-21  Product2    NaN   West         554.0
21  2023-01-22  Product3  296.0   West         296.0
22  2023-01-23  Product2  737.0   West         737.0
23  2023-01-24  Product3  531.0   East         531.0
24  2023-01-25  Product2  834.0  North         834.0